apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-rs
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: tomcat-rs
  template:
    metadata:
      labels:
        app: tomcat-rs
    spec:
      containers:
        - name: tomcat-rs
          image: tomcat:9.0.62
